### ISSUE TITLE
Настройка подключения двух устройств Neptun к одному Home Assistant

### ISSUE THREAD

**Issue by TolianIPB** [klim123123/neptun_smart_homeassistant#3]
Я сам не программист, но код немного умею читать.
Мне нужно подключить два устройтва. Когда пробовал понять код, сложилось впечатление, что он оптимизирован для одного устройства. Чтобы он работал для двух устройств, нужно будет весь код дублировать.
Если у Вас будет время, то пожалуйста помогите решить эту задачу как-то более эллегантно. Возможно с помощью переменных.

**Comment by latishev** [comment]
Клим выложил свою конфигурацию, пока что это больше похоже на отладочный код, совместными усилиями сделаем рабочий вариант для всех.

Для вас я вижу необходимость прописать всем Sensor и Switch уникальные name и unique_id, вот пример из кода

- name: "Number of Connected Wireless Sensors"
        address: 6
        slave: 240
        input_type: holding
        data_type: uint16
        unit_of_measurement: "шт."
        unique_id: "number_of_connected_wireless_sensors"
        scan_interval: 30

Прописать желательно так

- name: "**Neptun 1** Number of Connected Wireless Sensors"
        address: 6
        slave: 240
        input_type: holding
        data_type: uint16
        unit_of_measurement: "шт."
        unique_id: "**Neptun_1_**number_of_connected_wireless_sensors"
        scan_interval: 30

**Comment by klim123123** [comment]
У меня тоже стоят два Нептуна. Буду добавлять второй, обязательно подумаю как сделать это удобно, чтобы можно было сразу хоть 10 добавлять. Пока код сырой, я просто решил выложить как можно быстро. Т.к. сам ждал его уже много лет.
Вот получилось с третьего подхода и решил сразу поделится с комьюнити.

**Comment by klim123123** [comment]
полную конфигурацию выложу позже, но вообще нужно начать с первого пункта modbus
```
modbus:
  - name: neptun_smart
    type: tcp
    host: 192.168.1.198 #ип первого нептуна
    port: 503
    delay: 3
    timeout: 3
  - name: neptun_smart2
    type: tcp
    host: 192.168.1.199 #ип второго нептуна
    port: 503
    delay: 3
    timeout: 3
```
ну и далее по аналогии, только уже данные брать с отдельно с neptun_smart и neptun_smart2

**Comment by TolianIPB** [comment]
> У меня тоже стоят два Нептуна. Буду добавлять второй, обязательно подумаю как сделать это удобно, чтобы можно было сразу хоть 10 добавлять. Пока код сырой, я просто решил выложить как можно быстро. Т.к. сам ждал его уже много лет. Вот получилось с третьего подхода и решил сразу поделится с комьюнити.

Главное, что код рабочий! Вчера прям сразу без кикстарта завелось! СПАСИБО!

**Comment by AlexLIte** [comment]
Спасибо большое за работу, у меня не получилось завести Нептуны через localtuya, с твоим кодом интеграция завелась. 
Хочу поделиться своими потугами. После добавления шаблонов я захотел собрать их в одно единое устройство. Это можно сделать с помощью интеграции Device Tools [https://github.com/EuleMitKeule/device-tools](url), но заметил такую вещь, что можно добавлять только сущности с unique_id. Не знаю насколько правильно, я новичок в haos, я приписал unique_id  всем сущностям, и в связи с тем, что у меня 2 Нептуна в  квартире, я сразу задавал принадлежность сущности к определенной комнате, и приписал ее же к hub name устройства. У меня нет пока беспроводных датчиков протечки, так что весь код связанный с ними я закомментил, и там ничего не менял пока. Кому нужно, можно сделать по аналогии с остальными сущностями.  Может кому пригодится. Код правил в интеграции FIle Editor в haos, там же можно быстро раскомментить код и через ctrl+f вызвать внутренний поисковик с функицией замены текста по всему коду. Я так сделал для второго непнуна, заменив toilet на bathroom. В итоге собрал сущности в полноценное устройство. Пока не все переименовал.
![image](https://github.com/user-attachments/assets/620226db-1101-4777-b55c-a9f6d204297e)

Еще чтобы не перегружать configuration.yaml  вынес интеграцию в отдельный пакет, чтоб конфиг каждого нептуна лежал в отдельном файле

```
homeassistant:
...
  packages: !include_dir_named packages
```
![image](https://github.com/user-attachments/assets/2035106c-02b2-4b52-aa4b-9561941e4b4d)

```

modbus:
  - name: neptun_smart_toilet
    type: tcp
    host: 192.168.1.10
    port: 503
    delay: 3
    timeout: 3

    sensors:
      - name: "Toilet Neptun Alarm and Mode Raw"
        unique_id: "toilet_neptun_alarm_and_mode_raw"
        address: 0
        slave: 240
        input_type: holding
        data_type: uint16
        scan_interval: 10
      - name: "Toilet Neptun Leak Sensor Raw"
        unique_id: "toilet_neptun_leak_sensor_raw"
        address: 3
        slave: 240
        input_type: holding
        data_type: uint16
        scan_interval: 10

    #   - name: "Number of Connected Wireless Sensors"
    #     address: 6
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     unit_of_measurement: "шт."
    #     unique_id: "number_of_connected_wireless_sensors"
    #     scan_interval: 30
    #   - name: "Wireless Sensor 1 Raw"
    #     address: 57
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     scan_interval: 10

    #   - name: "Wireless Sensor 2 Raw"
    #     address: 58
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     scan_interval: 10

    #   - name: "Wireless Sensor 3 Raw"
    #     address: 59
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     scan_interval: 10

    #   - name: "Wireless Sensor 4 Raw"
    #     address: 60
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     scan_interval: 10

    #   - name: "Wireless Sensor 5 Raw"
    #     address: 61
    #     slave: 240
    #     input_type: holding
    #     data_type: uint16
    #     scan_interval: 10



# Template sensor для двоичного представления значения
template:
  sensor:
    - name: "Toilet Neptun Alarm and Mode Binary"
      unique_id: "toilet_neptun_alarm_and_mode_binary"
      state: "{{ '{:016b}'.format(states('sensor.toilet_neptun_alarm_and_mode_raw') | int) }}"  # Двоичное представление 16 бит

# ### Wireless sensors ####
#     - name: "Battery Level Sensor 1"
#       unit_of_measurement: "%"
#       state: "{{ ((states('sensor.wireless_sensor_1_raw') | int) // (2 ** 8)) % 256 }}"  # Извлечение битов 8–15
#       icon: mdi:battery

#     - name: "Sensor Signal Level 1"
#       unit_of_measurement: "%"
#       state: "{{ (((states('sensor.wireless_sensor_1_raw') | int) // (2 ** 3)) % 8) * 25 }}"  # Извлечение битов 3–5 и умножение на 25 для масштабирования
#       icon: mdi:signal

#     - name: "Battery Level Sensor 2"
#       unit_of_measurement: "%"
#       state: "{{ ((states('sensor.wireless_sensor_2_raw') | int) // (2 ** 8)) % 256 }}"
#       icon: mdi:battery

#     - name: "Sensor Signal Level 2"
#       unit_of_measurement: "%"
#       state: "{{ (((states('sensor.wireless_sensor_2_raw') | int) // (2 ** 3)) % 8) * 25 }}"
#       icon: mdi:signal

#     # Новые сенсоры для Sensor 3
#     - name: "Battery Level Sensor 3"
#       unit_of_measurement: "%"
#       state: "{{ ((states('sensor.wireless_sensor_3_raw') | int) // (2 ** 8)) % 256 }}"
#       icon: mdi:battery

#     - name: "Sensor Signal Level 3"
#       unit_of_measurement: "%"
#       state: "{{ (((states('sensor.wireless_sensor_3_raw') | int) // (2 ** 3)) % 8) * 25 }}"
#       icon: mdi:signal

#     # Новые сенсоры для Sensor 4
#     - name: "Battery Level Sensor 4"
#       unit_of_measurement: "%"
#       state: "{{ ((states('sensor.wireless_sensor_4_raw') | int) // (2 ** 8)) % 256 }}"
#       icon: mdi:battery

#     - name: "Sensor Signal Level 4"
#       unit_of_measurement: "%"
#       state: "{{ (((states('sensor.wireless_sensor_4_raw') | int) // (2 ** 3)) % 8) * 25 }}"
#       icon: mdi:signal

#     # Новые сенсоры для Sensor 5
#     - name: "Battery Level Sensor 5"
#       unit_of_measurement: "%"
#       state: "{{ ((states('sensor.wireless_sensor_5_raw') | int) // (2 ** 8)) % 256 }}"
#       icon: mdi:battery

#     - name: "Sensor Signal Level 5"
#       unit_of_measurement: "%"
#       state: "{{ (((states('sensor.wireless_sensor_5_raw') | int) // (2 ** 3)) % 8) * 25 }}"
#       icon: mdi:signal
# ### END Wireless sensors ####


# Template binary sensors для отдельных битов
  binary_sensor:
    - name: "Toilet Neptun Floor Washing Mode"
      unique_id: "toilet_neptun_floor_washing_mode"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[15] == '1' }}"  # 0-й бит

    - name: "Toilet Neptun Alarm zona 1"
      unique_id: "toilet_neptun_alarm_zona_1"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[14] == '1' }}"  # 1-й бит

    - name: "Toilet Neptun Alarm zona 2"
      unique_id: "toilet_neptun_alarm_zona_2"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[13] == '1' }}"  # 2-й бит

    - name: "Toilet Neptun LeakSensor 1"
      unique_id: "toilet_neptun_leak_sensor_1"
      state: "{{ states('sensor.toilet_neptun_leak_sensor_raw') | int | bitwise_and(1) > 0 }}"  # Бит 0 регистра 3

    - name: "Toilet Neptun LeakSensor 2"
      unique_id: "toilet_neptun_leak_sensor_2"
      state: "{{ states('sensor.toilet_neptun_leak_sensor_raw') | int | bitwise_and(2) > 0 }}"  # Бит 1 регистра 3

    - name: "Toilet Neptun LeakSensor 3"
      unique_id: "toilet_neptun_leak_sensor_3"
      state: "{{ states('sensor.toilet_neptun_leak_sensor_raw') | int | bitwise_and(4) > 0 }}"  # Бит 2 регистра 3

    - name: "Toilet Neptun LeakSensor 4"
      unique_id: "toilet_neptun_leak_sensor_4"
      state: "{{ states('sensor.toilet_neptun_leak_sensor_raw') | int | bitwise_and(8) > 0 }}"  # Бит 3 регистра 3

    - name: "Toilet Neptun Zona 1"
      unique_id: "toilet_neptun_zona_1"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[7] == '1' }}"  # 8-й бит

    - name: "Toilet Neptun Zona 2"
      unique_id: "toilet_neptun_zona_2"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[6] == '1' }}"  # 9-й бит

    - name: "Toilet Neptun Keypad Locks"
      unique_id: "toilet_neptun_keypad_locks"
      state: "{{ states('sensor.toilet_neptun_alarm_and_mode_binary')[3] == '1' }}"  # 12-й бит

### Wireless sensors ####
#     - name: "Presence of Alarm Sensor 1"
#       state: "{{ (states('sensor.wireless_sensor_1_raw') | int) % 2 == 1 }}"  # Проверка 0-го бита
#       icon: mdi:alarm
      
#     - name: "Availability of Category Sensor 1"
#       state: "{{ ((states('sensor.wireless_sensor_1_raw') | int) // (2 ** 1)) % 2 == 1 }}"
#       icon: mdi:check-circle

#     - name: "Sensor Loss Sensor 1"
#       state: "{{ ((states('sensor.wireless_sensor_1_raw') | int) // (2 ** 2)) % 2 == 1 }}"
#       icon: mdi:alert-circle

#     - name: "Presence of Alarm Sensor 2"
#       state: "{{ (states('sensor.wireless_sensor_2_raw') | int) % 2 == 1 }}"
#       icon: mdi:alarm

#     - name: "Availability of Category Sensor 2"
#       state: "{{ ((states('sensor.wireless_sensor_2_raw') | int) // (2 ** 1)) % 2 == 1 }}"
#       icon: mdi:check-circle

#     - name: "Sensor Loss Sensor 2"
#       state: "{{ ((states('sensor.wireless_sensor_2_raw') | int) // (2 ** 2)) % 2 == 1 }}"
#       icon: mdi:alert-circle

#     - name: "Presence of Alarm Sensor 3"
#       state: "{{ (states('sensor.wireless_sensor_3_raw') | int) % 2 == 1 }}"
#       icon: mdi:alarm

#     - name: "Availability of Category Sensor 3"
#       state: "{{ ((states('sensor.wireless_sensor_3_raw') | int) // (2 ** 1)) % 2 == 1 }}"
#       icon: mdi:check-circle

#     - name: "Sensor Loss Sensor 3"
#       state: "{{ ((states('sensor.wireless_sensor_3_raw') | int) // (2 ** 2)) % 2 == 1 }}"
#       icon: mdi:alert-circle

#     - name: "Presence of Alarm Sensor 4"
#       state: "{{ (states('sensor.wireless_sensor_4_raw') | int) % 2 == 1 }}"
#       icon: mdi:alarm

#     - name: "Availability of Category Sensor 4"
#       state: "{{ ((states('sensor.wireless_sensor_4_raw') | int) // (2 ** 1)) % 2 == 1 }}"
#       icon: mdi:check-circle

#     - name: "Sensor Loss Sensor 4"
#       state: "{{ ((states('sensor.wireless_sensor_4_raw') | int) // (2 ** 2)) % 2 == 1 }}"
#       icon: mdi:alert-circle

#     - name: "Presence of Alarm Sensor 5"
#       state: "{{ (states('sensor.wireless_sensor_5_raw') | int) % 2 == 1 }}"
#       icon: mdi:alarm

#     - name: "Availability of Category Sensor 5"
#       state: "{{ ((states('sensor.wireless_sensor_5_raw') | int) // (2 ** 1)) % 2 == 1 }}"
#       icon: mdi:check-circle

#     - name: "Sensor Loss Sensor 5"
#       state: "{{ ((states('sensor.wireless_sensor_5_raw') | int) // (2 ** 2)) % 2 == 1 }}"
#       icon: mdi:alert-circle

 ### END Wireless sensors ####


# Template binary_sensor для Dual Zone Mode
binary_sensor:
  - platform: template
    sensors:
      toilet_neptun_dual_zone_mode:
        friendly_name: "Toilet Neptun Dual Zone Mode"
        unique_id: "toilet_neptun_dual_zone_mode"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(1024) > 0 }}"  # 10-й бит
    #   battery_drain_wireless_sensors:
    #     friendly_name: "Battery Drain in Wireless Sensors"
    #     unique_id: "toilet_neptun_battery_drain_wireless_sensors"
    #     value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(8) > 0 }}"  # Проверка 3-го бита
    #     icon_template: >
    #       {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(8) > 0 %}
    #         mdi:battery-alert
    #       {% else %}
    #         mdi:battery
    #       {% endif %}

    #   lost_connection_wireless_sensors:
    #     friendly_name: "Lost Connection with Wireless Sensors"
    #     unique_id: "lost_connection_wireless_sensors"
    #     value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(16) > 0 }}"  # Проверка 4-го бита
    #     icon_template: >
    #       {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(16) > 0 %}
    #         mdi:signal-off
    #       {% else %}
    #         mdi:signal
    #       {% endif %}




# Template switches для управления Zona 1, Zona 2, и Zona 1 + Zona 2 с доступностью для Zona 2
switch:
  - platform: template
    switches:
      toilet_neptun_zona_1_switch:
        friendly_name: "Toilet Neptun Zona 1 Switch"
        unique_id: "toilet_neptun_zona_1_switch"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(256) > 0 }}"
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(256) > 0 %}
            mdi:water-pump
          {% else %}
            mdi:water-pump-off
          {% endif %}
        turn_on:
          service: modbus.write_register
          data_template:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: >
              {% if is_state('binary_sensor.toilet_neptun_dual_zone_mode', 'off') %}
                {{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(768) }}
              {% else %}
                {{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(256) }}
              {% endif %}
        turn_off:
          service: modbus.write_register
          data_template:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: >
              {% if is_state('binary_sensor.toilet_neptun_dual_zone_mode', 'off') %}
                {{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(768)) }}
              {% else %}
                {{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(256)) }}
              {% endif %}


      toilet_neptun_zona_2_switch:
        friendly_name: "Toilet Neptun Zona 2 Switch"
        unique_id: "toilet_neptun_zona_2_switch"
        availability_template: "{{ is_state('binary_sensor.toilet_neptun_dual_zone_mode', 'on') }}"  # Доступен только если Dual Zone Mode включён
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(512) > 0 }}"
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(512) > 0 %}
            mdi:water-pump
          {% else %}
            mdi:water-pump-off
          {% endif %}
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(512) }}"
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(512)) }}"

      toilet_neptun_zona_1_2_switch:
        friendly_name: "Toilet Neptun Zona 1 + Zona 2 Switch"
        unique_id: "toilet_neptun_zona_1_2_switch"
        value_template: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(256)) > 0 and (states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(512)) > 0 }}"
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(768) }}"  # Устанавливаем 256 и 512 одновременно
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(768)) }}"  # Обнуляем 256 и 512

      toilet_neptun_dual_zone_mode_switch:
        friendly_name: "Toilet Neptun Dual Zone Mode Switch"
        unique_id: "toilet_neptun_dual_zone_mode_switch"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(1024) > 0 }}"  # Проверка 10-го бита
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(1024) > 0 %}
            mdi:tally-mark-2
          {% else %}
            mdi:tally-mark-1
          {% endif %}
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(1024) }}"  # Устанавливаем 10-й бит
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(1024)) }}"  # Обнуляем 10-й бит

      toilet_neptun_floor_washing_mode_switch:
        friendly_name: "Toilet Neptun Floor Washing Mode Switch"
        unique_id: "toilet_neptun_floor_washing_mode_switch"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(1) > 0 }}"  # Проверка 0-го бита
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(1) > 0 %}
            mdi:shower
          {% else %}
            mdi:shower-head
          {% endif %}
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(1) }}"  # Устанавливаем 0-й бит
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(1)) }}"  # Обнуляем 0-й бит

      toilet_neptun_keypad_locks_switch:
        friendly_name: "Toilet Neptun Keypad Locks Switch"
        unique_id: "toilet_neptun_keypad_locks_switch"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(4096) > 0 }}"  # Проверка 12-го бита
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(4096) > 0 %}
            mdi:keyboard-off
          {% else %}
            mdi:keyboard
          {% endif %}
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(4096) }}"  # Устанавливаем 12-й бит
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(4096)) }}"  # Обнуляем 12-й бит

      toilet_neptun_closing_taps_on_sensor_lost:
        friendly_name: "Toilet Neptun Closing Taps on Sensor Lost"
        unique_id: "toilet_neptun_closing_taps_on_sensor_lost_switch"
        value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(2048) > 0 }}"  # Проверка 11-го бита
        icon_template: >
          {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(2048) > 0 %}
            mdi:water-off
          {% else %}
            mdi:water
          {% endif %}
        turn_on:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(2048) }}"  # Устанавливаем 11-й бит
        turn_off:
          service: modbus.write_register
          data:
            hub: neptun_smart_toilet
            unit: 240
            address: 0
            value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.neptun_alarm_and_mode_raw') | int) | bitwise_and(2048)) }}"  # Обнуляем 11-й бит

    #   procedure_for_connecting_wireless_devices:
    #     friendly_name: "Procedure for Connecting Wireless Devices"
    #     unique_id: "toilet_neptun_procedure_for_connecting_wireless_devices_switch"
    #     value_template: "{{ states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(128) > 0 }}"  # Проверка 7-го бита
    #     icon_template: >
    #       {% if states('sensor.toilet_neptun_alarm_and_mode_raw') | int | bitwise_and(128) > 0 %}
    #         mdi:wifi
    #       {% else %}
    #         mdi:wifi-off
    #       {% endif %}
    #     turn_on:
    #       service: modbus.write_register
    #       data:
    #         hub: neptun_smart_toilet
    #         unit: 240
    #         address: 0
    #         value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_or(128) }}"  # Устанавливаем 7-й бит
    #     turn_off:
    #       service: modbus.write_register
    #       data:
    #         hub: neptun_smart_toilet
    #         unit: 240
    #         address: 0
    #         value: "{{ (states('sensor.toilet_neptun_alarm_and_mode_raw') | int) - ((states('sensor.toilet_neptun_alarm_and_mode_raw') | int) | bitwise_and(128)) }}"  # Обнуляем 7-й бит
```
